package internal

import (
	"context"
	"fmt"
	"github.com/go-chi/chi/v5"
	"github.com/go-chi/chi/v5/middleware"
	"github.com/go-chi/cors"
	"github.com/pkg/errors"
	_ "github.com/swaggo/http-swagger/example/go-chi/docs" // docs is generated by Swag CLI, you have to import it.
	"itrevolution-backend/internal/controllers"
	"itrevolution-backend/internal/controllers/auth"
	"itrevolution-backend/internal/domain"
	"itrevolution-backend/internal/types"
	"net/http"
	"strings"
	"time"
)

func Run(ctx context.Context, serverCtx types.ServerContext) {
	r := chi.NewRouter()

	r.Use(middleware.Logger)
	r.Use(middleware.Timeout(60 * time.Second))
	r.Use(contextMiddleware(serverCtx))
	r.Use(cors.Handler(cors.Options{
		AllowedOrigins:   []string{"*"},
		AllowedMethods:   []string{"GET", "POST", "PATCH", "DELETE", "OPTIONS"},
		AllowedHeaders:   []string{"Accept", "Authorization", "Content-Type", "X-CSRF-Token"},
		ExposedHeaders:   []string{"Link"},
		AllowCredentials: true,
		MaxAge:           300, // Maximum value not ignored by any of major browsers
	}))
	r.Use(middleware.Recoverer)

	r.Route("/api/auth", func(r chi.Router) {
		r.Post("/refresh_token", auth.RefreshToken)
		r.Post("/register", auth.Register)
		r.Post("/login", auth.Login)
		r.Post("/code", auth.RegisterCode)
	})

	r.Route("/api/users", func(r chi.Router) {
		r.Get("/me", roleGuard([]string{"*"}, controllers.UsersGetMe))
		r.Get("/", roleGuard([]string{"*"}, controllers.UsersGetAll))
		r.Patch("/me", roleGuard([]string{"*"}, controllers.UsersUpdateMe))
	})

	go func() {
		serverCtx.Log.Info("Server is listening")
		if err := http.ListenAndServe(fmt.Sprintf("0.0.0.0:%v", serverCtx.Config.Port), r); err != nil {
			serverCtx.Log.Fatal(err)
		}
	}()
}

func contextMiddleware(serverCtx types.ServerContext) func(next http.Handler) http.Handler {
	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			ctx := context.WithValue(r.Context(), "server", serverCtx)
			next.ServeHTTP(w, r.WithContext(ctx))
		})
	}
}

func roleGuard(roles []string, next http.HandlerFunc) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		serverCtx := r.Context().Value("server").(types.ServerContext)
		authorization := r.Header.Get("Authorization")

		parsedAuthorization := strings.Split(authorization, " ")
		if len(parsedAuthorization) == 2 {
			user, err := auth.GetUserFromAccessToken(serverCtx, parsedAuthorization[1])
			if err != nil {
				domain.HTTPError(w, r, http.StatusUnauthorized, nil)
				return
			}
			if !user.IsRegistered {
				domain.HTTPError(w, r, http.StatusUnauthorized, errors.New("Your account is not activated. Check your email and try again."))
			}
			for _, role := range roles {
				if role == "*" || role == user.Role {
					ctx := context.WithValue(r.Context(), "user", user)
					next.ServeHTTP(w, r.WithContext(ctx))
					return
				}
			}
			w.WriteHeader(http.StatusForbidden)
		} else {
			w.WriteHeader(http.StatusUnauthorized)
			return
		}
	}
}
